spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://dev-db:3306/mydatabase}
    username: ${DB_USERNAME:myuser}
    password: ${DB_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
