### 전체 조회
GET {{host}}/api/v1/hello

### 단건 조회
GET {{host}}/api/v1/hello/1

### 생성
POST {{host}}/api/v1/hello
Content-Type: application/json

{
  "message": "Hello, World!"
}

### 수정
PUT {{host}}/api/v1/hello/1
Content-Type: application/json

{
  "message": "Updated Message"
}

### 삭제
DELETE {{host}}/api/v1/hello/1
